[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pss-export"
version = "0.1.0"
description = "Export models from the Plant Stress Signalling (PSS) Neo4j knowledge graph to various file formats."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Carissa Bleker", email = "carissa.bleker@nib.si"}
]
maintainers = [
    {name = "Carissa Bleker", email = "carissa.bleker@nib.si"}
]
keywords = [
    "systems biology",
    "knowledge graph",
    "SBML",
    "Neo4j",
    "plant stress signalling",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Systems Biology"
]

# Core dependencies
dependencies = [
    "neo4j>=5.28",
    "python-libsbml>=5.19.0",
    "tabularqual>=0.1.0",
    "pyyaml>=5.4",
    "click>=8.0",
    "python-dotenv>=0.19.0",
    "pandas>=1.3.0",
    "networkx>=2.6",
    "rich>=10.0",
    "matplotlib>=3.4",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[project.urls]
Homepage = "https://github.com/NIB-SI/pss-export"

[project.scripts]
pss-export = "pss_export.cli:cli"

[tool.setuptools]
packages = ["pss_export"]

[tool.setuptools.package-data]
pss_export = ["*.yaml", "*.yml"]
