# Settings and mappings for exporting PSS from db to other formats


#-------------------------
# Export settings
#-------------------------

# Nodes to ignore when exporting
# Based on the node "name" attribute
nodes_to_ignore:
  - GA|GID1|SLR1
  - SLR1[LOC_OS06G03710]
  - GID|SCF
  - SCF
  - D14|MAX2|SCF
  - COI1|JA-Ile|SCF
  - EBF|SCF
  - RISC - miR390
  - CML12|PID
  - PBP1|PID
  - CMI1|ICR1
  # just for testing:
  - LST8[AT2G22040,AT3G18140]
  - FLS2[AT5G46330]
  - FKBP62[AT3G25230]
  - RAR1[AT5G51700]
  - HSP70[AT3G12580]

#-------------------------
# Renaming settings
#-------------------------
# Used to generate IDs for species in Boolnet, SBML, SBGN

compartment_to_short:
  apoplast: 'ap'
  chloroplast: 'chl'
  cytoplasm: 'cyt'
  endoplasmic reticulum: 'er'
  extracellular: 'x'
  golgi apparatus: 'ga'
  mitochondrion: 'mit'
  nucleolus: 'nucl'
  nucleus: 'nuc'
  peroxisome: 'per'
  unknown: 'cyt'
  vacuole: 'vac'
  none: 'none'

node_form_to_short:
  abiotic: 'ab'
  complex: 'c'
  complex_active: 'ca'
  foreign_entity: 'f'
  gene: 'g'
  metabolite: 'm'
  mirna: 'mi'
  mrna: 'mr'
  ncrna: 'nc'
  process: 'pr'
  process_active: 'pra'
  protein: 'p'
  protein_active: 'pa'
  abstract: 'abst'
  abstract_active: 'absta'

#-------------------------
# SBO annotations
#-------------------------

compartment_to_SBO: '0000410'

# annotate species in listOfSpecies
# according to SBML l3v2,  should be child of 'physical entity representation' SBO:0000236
# Note: https://github.com/EBI-BioModels/SBO/issues/5
node_form_to_SBO:
  # Following are children of 'material entity' ('correct' according to above issue)
  metabolite:       '0000247' # simple chemical
  protein:          '0000297' # protein complex, alternative: 252-polypeptide chain
  protein_active:   '0000297' # protein complex, alternative: 252-polypeptide chain
  gene:             '0000243' # gene
  process:          '0000375' # process
  process_active:   '0000375' # process
  complex:          '0000296' # macromolecular complex, alternative: 253-chemical macromolecule
  complex_active:   '0000296' # macromolecular complex, alternative: 253-chemical macromolecule
  unknown:          '0000285' # material entity of unspecified nature
  abstract:         '0000285' # material entity of unspecified nature
  abstract_active:  '0000285' # material entity of unspecified nature

  foreign_entity:   '0000405' # perturbing agent
  abiotic:          '0000405' # perturbing agent

  # Following are children of 'unit of genetic information' ('incorrect' according to above issue)
  mrna:             '0000278' # messenger RNA, alternative:0000250-ribonucleic acid
  mirna:            '0000316' # microRNA
  ncrna:            '0000334' # non-coding RNA
  ta-sirna:         '0000334' # non-coding RNA

# annotate reactions in listOfReactions
# (1) reaction type: according to SBML l3v2, should be child of 'occurring entity representation' SBO:0000231
# (2) kinetic law: according to SBML l3v2, should be child of 'mathematical expression' SBO:0000244
reaction_subtype_to_SBO:
  binding-with-modifier:
    reaction_type_SBO: '0000177' # non-covalent binding (PPI=non-covalent), alternative: 0000344-molecular interaction
    kinetic_law_SBO:   '0000528' # common modular rate law
  binding-without-modifier:
    reaction_type_SBO: '0000177' # non-covalent binding (PPI=non-covalent), alternative: 0000344-molecular interaction
    kinetic_law_SBO:   '0000528' # common modular rate law

  dissociation-with-modifier:
    reaction_type_SBO: '0000180' # dissociation (non-covalent complex to independent biochemical entities)
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  dissociation-without-modifier:
    reaction_type_SBO: '0000015' # dissociation (non-covalent complex to independent biochemical entities)
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law

  catalysis-with-substrate-and-with-modifier:
    reaction_type_SBO: '0000176' # biochemical reaction
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  catalysis-without-substrate-and-with-modifier:
    reaction_type_SBO: '0000176' # biochemical reaction
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  catalysis-with-substrate-and-without-modifier:
    reaction_type_SBO: '0000176' # biochemical reaction (OR 0000672 - spontaneous reaction)
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  catalysis-without-substrate-and-without-modifier:
    reaction_type_SBO: '0000176' # spontaneous reaction (OR 0000672 - spontaneous reaction)
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law

  degradation-with-modifier:
    reaction_type_SBO: '0000179' # degradation
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  degradation-without-modifier:
    reaction_type_SBO: '0000179' # degradation
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law

  protein-activation-with-modifier:
    reaction_type_SBO: '0000656' # activation (conformational change of a protein)
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law

  protein-deactivation-with-modifier:
    reaction_type_SBO: '0000665' # inactivation (conformational change of a protein)
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law

  transcriptional-activation-with-modifier:
    reaction_type_SBO: '0000589' # genetic production (OR 0000183 - transcription)
    kinetic_law_SBO:   '0000198' # Hill-type rate law, reduced form
  translational-activation-with-modifier:
    reaction_type_SBO: '0000589' # genetic production (OR 0000184 - translation)
    kinetic_law_SBO:   '0000198' # Hill-type rate law, reduced form
  transcriptional-or-translational-activation-with-modifier:
    reaction_type_SBO: '0000589' # genetic production (OR 0000183 - transcription)
    kinetic_law_SBO:   '0000198' # Hill-type rate law, reduced form

  transcriptional-repression-with-modifier:
    reaction_type_SBO: '0000589' # genetic production (OR 0000183 - transcription)
    kinetic_law_SBO:   '0000198' # Hill-type rate law, reduced form
  translational-repression-with-modifier:
    reaction_type_SBO: '0000589' # genetic production (OR 0000183 - transcription)
    kinetic_law_SBO:   '0000198' # Hill-type rate law, reduced form
  transcriptional-or-translational-repression-with-modifier:
    reaction_type_SBO: '0000589' # genetic production (OR 0000183 - transcription)
    kinetic_law_SBO:   '0000198' # Hill-type rate law, reduced form

  translocation-with-modifier:
    reaction_type_SBO: '0000657' # active transport
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  translocation-without-modifier:
    reaction_type_SBO: '0000658' # passive transport
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law

  unknown-activation-with-modifier:
    reaction_type_SBO: '0000176' # biochemical reaction
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  unknown-activation-without-modifier:
    reaction_type_SBO: '0000176' # biochemical reaction
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  unknown-inhibition-with-modifier:
    reaction_type_SBO: '0000176' # biochemical reaction
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law
  unknown-inhibition-without-modifier:
    reaction_type_SBO: '0000176' # biochemical reaction
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law

  unknown:
    reaction_type_SBO: '0000176' # biochemical reaction
    kinetic_law_SBO:   '0000029' # Henri-Michaelis-Menten rate law

# annotate species role in the reactions in speciesReference (per reaction)
# according to SBML l3v2, should be child of 'participant role' SBO:0000003
node_role_to_SBO:
  # modifiers
  modifier:    '0000019' # modifier
  enzyme:      '0000460' # enzymatic catalyst
  transporter: '0000248' # transporter
  receptor:    '0000244' # receptor
  stimulator:  '0000459' # stimulator
  inhibitor:   '0000020' # inhibitor

  # products
  product:     '0000011' # product

  # reactants
  interactor:  '0000336' # interactor
  substrate:   '0000015' # substrate
  template:    '0000645' # template

#-------------------------
# SBGN settings
#-------------------------

label_to_class:
  Metabolite: SIMPLE_CHEMICAL
  MetaboliteFamily: SIMPLE_CHEMICAL
  ForeignCoding: MACROMOLECULE
  PlantCoding: MACROMOLECULE
  Complex: COMPLEX
  Process: UNSPECIFIED_ENTITY
  PlantAbstract: UNSPECIFIED_ENTITY
  ForeignEntity: UNSPECIFIED_ENTITY
  ForeignAbiotic: PERTURBING_AGENT

label_to_form:
  Metabolite: metabolite
  MetaboliteFamily: metabolite
  ForeignCoding: protein
  PlantCoding: protein
  Complex: complex
  Process: process
  PlantAbstract: protein
  ForeignEntity: foreign_entity
  ForeignAbiotic: abiotic

form_to_state:
  na: null
  metabolite: null
  protein: inactive
  protein_active: active
  gene: null
  mrna: null
  mirna: null
  ncrna: null
  process: inactive
  process_active: active
  complex: inactive
  complex_active: active
  abiotic: null
  foreign_entity: null

reaction_type_to_process:
  catalysis/auto-catalysis: PROCESS
  catalysis: PROCESS
  cleavage/auto-cleavage: PROCESS
  protein activation: PROCESS
  degradation/secretion: PROCESS
  translocation: PROCESS
  undefined: PROCESS
  protein deactivation: PROCESS
  transcriptional/translational repression: PROCESS
  transcriptional/translational induction: PROCESS
  transcriptional/translational activation: PROCESS
  binding/oligomerisation: ASSOCIATION
  dissociation: DISSOCIATION
  unknown: PROCESS

edge_to_arc:
  catalysis/auto-catalysis:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: CATALYSIS
  catalysis:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: CATALYSIS
  cleavage/auto-cleavage:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: CATALYSIS
  protein activation:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: STIMULATION
  protein deactivation:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: STIMULATION
  degradation/secretion:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: CATALYSIS
  binding/oligomerisation:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: CATALYSIS
  dissociation:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: CATALYSIS
  translocation:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: STIMULATION
  transcriptional/translational induction:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: STIMULATION
  transcriptional/translational activation:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: STIMULATION
  transcriptional/translational repression:
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    MODIFIER: INHIBITION
  unknown:
    ACTIVATES: STIMULATION
    INHIBITS: INHIBITION
    PRODUCT: PRODUCTION
    SUBSTRATE: CONSUMPTION
    TRANSLOCATE_FROM: CONSUMPTION
    TRANSLOCATE_TO: PRODUCTION
    MODIFIER: CATALYSIS

# The colours are in hex format
form_to_colour:
  metabolite: '#abb0d0'
  protein: '#7fffd4'
  protein_active: '#7fffd4'
  gene: '#006b47'
  mrna: '#006b47'
  mirna: '#77c0c9'
  ncrna: '#77c0c9'
  process: '#a239fa'
  process_active: '#a239fa'
  complex: '#ffefd5'
  complex_active: '#ffefd5'
  reaction: '#ffffff'
  protein_state: '#e0e0e0'
  protein_active_state: '#ffffff'
  process_state: '#e0e0e0'
  process_active_state: '#ffffff'
  complex_state: '#e0e0e0'
  complex_active_state: '#ffffff'
  foreign_entity: '#f2a1bd'
  compartment: '#ebebeb'
  arc: '#555555'
  abiotic: '#f2a1bd'

compartment_to_colour:
  cytoplasm: '#c8c831'
  chloroplast: '#228b22'
  endoplasmic reticulum: '#f16f36'
  golgi apparatus: '#e69500'
  nucleus: '#8b2257'
  peroxisome: '#2200e6'
  vacuole: '#31c8c8'
  mitochondrion: '#adff2f'
  apoplast: '#1b1b07'
  nucleolus: '#c8317d'
  extracellular: '#f5f5dc'